config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "pages#home"
  resources :users, only: %i[show]
  resources :bookings, only: %i[destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :rooms do
    resources :bookings, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :starts_at, presence: true
  validates :ends_at, presence: true

  attr_accessor :date_range

  def total_price
    nights = (self.ends_at.to_date - self.starts_at.to_date).to_i
    total = self.room.price_per_night * nights
    return total
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :bookings, through: :rooms, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings, dependent: :destroy
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :price_per_night, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @booking = Booking.new(booking_params)
    @room = Room.find(params[:room_id])
    @booking.user = current_user
    @booking.room = @room

    date_range_string = params[:booking][:date_range]
    dates = date_range_string.split(' to ')
    starts_at = dates[0]&.strip
    ends_at = dates[1]&.strip
    @booking.starts_at = starts_at
    @booking.ends_at = ends_at
    if @booking.save
      redirect_to user_path(current_user), notice: "Réservation réussie. Consultez vos réservations dans votre espace personnel."
    else
      @room = Room.find(params[:room_id])
      flash.now[:alert] = "Erreur de réservation, indiquez des dates correctes."
      render "rooms/show", status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_path(current_user), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:date_range, :user_id, :room_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBookRoomsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <!-- Hotjar Tracking Code for https://www.dev-certif.online -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:3803973,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner hero-index">
  <div class="container hero-details">
    <h1 class="display-3 text-white hero-title">Les meilleures chambres d'hôtel</h1>
    <h1 class="display-3 text-white mb-4 hero-title">à des prix réduits !</h1>
    <%= link_to "Voir nos offres", rooms_path, class: "btn btn-light custom-bg-color" %>
  </div>
  <div class="position-absolute bottom-0 w-100 text-center mb-4">
    <h3 class="text-white">Suivez-nous !</h3>
  </div>
</div>

<div class="icon-container text-center">
  <a href="#">
    <i class="fa-brands fa-instagram"></i>
  </a>
  <a href="#">
    <i class="fa-brands fa-facebook-f"></i>
  </a>
</div>

app/views/rooms/index.html.erb
<div class="container mt-4 mb-5" data-controller="async-image-loader">
  <h1 class="mb-3">Chambres disponibles</h1>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-3">
    <% @rooms.each do |room| %>
      <div class="col">
        <div class="card card-with-margin" style="width: 18rem;">
          <%= image_tag room.photo, class: "card-img-top img-fluid img-size async-image", data: { room_photo: room.photo } %>
          <div class="card-body d-flex flex-column">
            <h4 class="card-title text-center mb-3"><%= room.hotel.name %></h4>
            <div class="d-flex justify-content-between">
              <%= link_to "Détails", room_path(room), class: "btn btn-light custom-bg-color" %>
              <h5 class="card-title mt-2"><%= room.price_per_night %>€ / nuit</h5>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-4">
      <div class="card" style="width: 25rem;">
        <%= image_tag "#{@room.photo}",
                      class: "card-img-top img-fluid img-size",
                      style: "height: 20rem;" %>
        <div class="card-body">
          <h4 class="card-title mb-3"><%= @room.hotel.name %></h4>
          <p class="card-title">Capacité : <%= @room.capacity %> personnes</p>
          <p class="card-title">Adresse : <%= @room.hotel.address %></p>
          <h5 class="card-title mt-2"><%= @room.price_per_night %>€ / nuit</h5>
        </div>
      </div>
    </div>
    <div class="col-6">
      <div class="border p-4">
        <h1 class="mb-4">Complétez votre réservation</h1>

        <%= simple_form_for [@room, @booking] do |f| %>
          <div class="row mb-3">
            <div class="form-group">
            <%= f.label :date_range, "Choisir les dates" %>
            <%= f.input :date_range, as: :string, label: false, input_html: { class: "form-control", data: { controller: "datepicker" } } %>
          </div>
          <div class="row">
            <div class="col">
              <%= f.submit "Je réserve cette chambre", class: "btn btn-light custom-bg-color" %>
              <%= link_to "Retour", rooms_path, class: "btn btn-dark ms-2" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h2 class="mt-2 ms-2">ToGoToSleep</h2> 
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Nos offres", rooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Espace personnel", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://cdn3.iconfinder.com/data/icons/essential-rounded/64/Rounded-31-512.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Paramètres", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-4 mb-5">
  <h3 class="mt-4 mb-4">Mes infos personnelles</h3>
  <p>email : <%= current_user.email %></p>
  <p>Date de création du profil : <%=  current_user.created_at.strftime("%d %B %Y") %></p>
  <%= link_to "Editer mon profil", edit_user_registration_path, class:"btn btn-light custom-bg-color"   %>
</div>



<div class="container mt-4 mb-5">
  <% if @user.bookings.present? %>
    <% future_bookings = @user.bookings.select { |booking| booking.ends_at > Date.today } %>
    <% past_bookings = @user.bookings.select { |booking| booking.ends_at < Date.today } %>

    <% if future_bookings.present? %>
      <h3 class="mt-4 mb-4">Mes réservations à venir</h3>
      <div class="row row-cols-1 row-cols-md-4 g-2">
        <% future_bookings.each do |booking| %>
          <div class="col mb-3">
            <div class="card" style="width: 18rem;">
              <%= image_tag "#{booking.room.photo}", class:"card-img-top img-fluid img-size" %>
              <div class="card-body">
                <h4 class="card-title"><%= booking.room.hotel.name %></h4>
                <p class="card-text"><%= booking.room.hotel.address %></p>
                <p class="card-text"><em>Réservée du <br>
                  <%= booking.starts_at.strftime('%d-%m-%Y') %> au <%= booking.ends_at.strftime('%d-%m-%Y') %></em>
                <p class="card-text">total : <%= booking.total_price %>€</p>
                <%= link_to "Annuler", booking_path(booking), class: "btn btn-dark custom-bg-color2", data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir annuler cette réservation ?"} %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if past_bookings.present? %>
      <h3 class="mt-4 mb-4">Mes réservations passées</h3>
      <div class="row row-cols-1 row-cols-md-3 g-2">
        <% past_bookings.each do |booking| %>
          <div class="col-4 mb-3">
            <div class="card" style="width: 18rem;">
              <%= image_tag "#{booking.room.photo}", class:"card-img-top img-fluid img-size" %>
              <div class="card-body">
                <h4 class="card-title"><%= booking.room.hotel.name %></h4>
                <p class="card-text"><%= booking.room.hotel.address %></p>
                <p class="card-text">
                  <em>Réservée du <br>
                  <%= booking.starts_at.strftime('%d-%m-%Y') %> au <%= booking.ends_at.strftime('%d-%m-%Y') %></em>
                </p>
                <p class="card-text">total : <%= booking.total_price %>€</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  <% else %>
    <p>Aucune réservation.</p>
  <% end %>
</div>